import type { Metadata } from "next";
import { auth } from "../auth";
import styles from "./layout.module.css";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.auth();

  const signOut = async () => {
    "use server";
    await auth.signOut();
  };

  return (
    <html>
      <body className={styles.body}>
        {children}
        {session ? (
          <form action={signOut}>
            <button className={styles.auth}>ログアウト</button>
          </form>
        ) : (
          <Link href="/sign-in" className={styles.auth}>
            ログイン
          </Link>
        )}
      </body>
    </html>
  );
}
